apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  namespace: manar-tawazun
  labels:
    app: deploy
    service: tawazun-svc
    name: ManarAlolasi
spec:
  template:
    metadata:
      name: deploy
      labels:
        app: deploy
        service: tawazun-svc
    spec:
      containers:
       - name: nginx
         image: 7111418/tawazun:latest
         ports:
            - containerPort: 8080
         args:
          - /bin/sh
          - -c
          - touch /tmp/healthy;
         livenessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 3
            failureThreshold: 5
         readinessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 3
            failureThreshold: 5
         startupProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 3
            failureThreshold: 5
  replicas: 1
  selector:
    matchLabels:
      app: deploy
      service: tawazun-svc
