apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-service
  namespace: manar-tawazun
  labels:
    app: deploy
    name: ManarAlolasi
spec:
  type: ClusterIP
  ports:
    - name: sql-port
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: deploy
